### PR TITLE
Fix kagome-adapter build

### PR DESCRIPTION
**Pull request by igor-egorov**

### CODE REVIEW

**Comment by igor-egorov** [comment]
Hello
@FlorianFranzen, could you please trigger the CI?

**Comment by FlorianFranzen** [comment]
Could you please base you work on `dependabot/submodules/hosts/kagome-8e9c10d` (see #23 for details)? Also, what did you use to reformat the source code?

**Comment by FlorianFranzen** [comment]
Looks like your are not installing all required headers at the moment, e.g. `consensus/babe/types/epoch_digest.hpp` is missing.

**Comment by igor-egorov** [comment]
Hi @FlorianFranzen. To reformat the code I used just clang-format. 
Unfortunately, I don't have write access to the branch you mentioned, thus I've updated that branch - the include directories issue is fixed via kagome host updating. It was also updated with the changes from your branch too.

I've tested this locally and kagome-adapter can be built now.

Could you please merge that branch into `dependabot/submodules/hosts/kagome-8e9c10d` to ensure everything works well and then we could close this pull request. Thanks! :)

**Comment by FlorianFranzen** [comment]
Thank you for fixing the header installation upstream. All I had to do in the end was update to the latest kagome.

**Pull request closed without merging**
